Closes #116 IndexedDB integration for service workers
tinyplex/tinybase pull request #128
Opened 2024-01-27 20:44 UTC by devjume

## Summary

- Closes issue #116
- IndexedDB integration can now be used with service workers, such as in Chrome extensions' background.js files.

## How did you test this change?

Ran all the tests successfully and confirmed that the fix indeed works with my own Chrome extension.

## Side note:
Didn't add any new tests. After reviewing the codebase, I believe it may not be necessary to add them, but I'm not entirely sure of this. Further review or feedback might be helpful.

2024-02-02 00:12 UTC, jamesgpearce commented
WOW! Sorry I haven't looked at this yet - I've been on a boat offshore for the last few days! I'll review this tomorrow and let's get this going. ❤️❤️❤️

2024-02-02 01:53 UTC, jamesgpearce requested changes
Looks good. I'll try and test it out tomorrow.

One syntactic thing if you could: the TinyBase house style would be to use a ternary here, since it minifies a bit better (ie `const request = condition ? if : else;`

2024-02-02 20:29 UTC, devjume commented
I refactored the code and ran the tests.

2024-02-03 15:05 UTC, merged

2024-02-03 15:05 UTC, jamesgpearce commented
Awesome! Let's go for it. I wonder if we should eventually use `globalThis` but this will work for now. Thank you again!