Create powersync persister
tinyplex/tinybase pull request #133
Opened 2024-02-21 11:43 UTC by bndkt

## Summary

Following on the heels of https://github.com/tinyplex/tinybase/pull/131, this is the PR to add the PowerSync persister to TinyBase. I'm submitting this in draft mode to give you a preview @jamesgpearce. Unfortunately I'm struggling to get the Jest unit tests working because the PowerSync SDK relies on Workers which are not available in Jest.

## How did you test this change?

Implemented the persister in a React Native demo app: https://github.com/bndkt/powerchat-tinybase/blob/tinybase/src/app/(app)/tinybase.tsx

Jest unit tests are failing, like described above.

2024-02-21 12:41 UTC, jamesgpearce requested changes
Again, amazing what you've been able to figure out in this codebase :)

I'm tempted to say we don't need to worry too much about the tests. We don't explicitly test expo and electric either, because the environments are so hard to replicate.

But is there anyway to mock workers in Jest? eg jsdom-worker? I realize this may not be trivial, but since this is the only persister using the conflict flag, we may need to do something just to keep the coverage at 100%

2024-02-21 12:41 UTC, jamesgpearce commented on src/persisters/persister-powersync.ts
> +    (listener: UpdateListener): AbortController => {
'AbortController' is a strange name for their listener handle!

2024-02-21 12:41 UTC, jamesgpearce commented on src/types/docs/persisters/persister-powersync.js
> +   * ```js yolo
hahaha you found the 'yolo' trick :)

2024-02-21 12:41 UTC, jamesgpearce commented on src/types/docs/persisters/persister-powersync.js
> + * @since v4.6.9
We'll make this feature into the 4.7 release.

2024-02-22 01:27 UTC, bndkt commented on src/persisters/persister-powersync.ts
> +    (listener: UpdateListener): AbortController => {
Agreed, but they just use the standard https://developer.mozilla.org/en-US/docs/Web/API/AbortController

2024-02-22 01:28 UTC, bndkt commented on src/persisters/persister-powersync.ts
> +        for await (const update of powerSync.onChange({
powerSync.onChange returns an async iterable, which I don't know that there is another way to loop over this. I've made this piece a bit cleaner and easier to read, but I think there's no way around the IIFE.

2024-02-22 02:45 UTC, bndkt commented
Thanks for the feedback again @jamesgpearce! Regarding the test, I tried using jsdom-worker, tried mocks, but couldn't get it to run. I spoke to PowerSync, they're working on making it work with Jest themselves, so maybe in the future there will be a chance to add this. What I did for now is a bit unconventional, curious what you think. In the end PowerSync is just using a sqlite database locally and the sync part with their service wouldn't be part of the tests anyways. So I created a mock (https://github.com/bndkt/tinybase/blob/46dcf0e96fed009963294cfc2c366d606f206413/test/unit/persisters/sqlite.ts#L52-L118, happy to move this into a separate file) which uses a simple sqlite database (just like the sqlite persister) but mimics the PowerSync interface. Now I "only" get 14 failing tests which are related to granular saves and the difference in SQL statements. I'll have to spent a few brain cycles on granular saves and the missing ON CONFLICT capability in PowerSync, will post about that separately.

2024-02-22 16:03 UTC, jamesgpearce commented on src/persisters/persister-powersync.ts
> +        for await (const update of powerSync.onChange({
Well ok - but it will be the only `for` in the whole codebase :)

2024-02-24 18:23 UTC, jamesgpearce commented
I'm hanging out here but take it out of draft when you want me to take a final look

2024-03-02 13:34 UTC, jamesgpearce commented
Hey @bndkt is this ready? 😄  - do you want me to review and/or rebase this for you?

2024-03-05 07:29 UTC, bndkt commented
Hey @jamesgpearce, thanks for checking in! I've poured a lot of time into fixing the tests now, but I'm afraid I need your help at this point. If you run the unit tests in this PR, you'll find 15 failing test. From my understanding, those can be put into two buckets:

- If you set useOnConflict to true for the PowerSync persister (exactly [here](https://github.com/bndkt/tinybase/blob/97ace7c8694f9f1ad872e60e75c16870bbaec9e5/src/persisters/persister-powersync.ts#L45)), there's only 3 tests that fail, all of which are related to autoLoad. Those must be due to a problem with my PowerSync [mock implementation](https://github.com/bndkt/tinybase/blob/97ace7c8694f9f1ad872e60e75c16870bbaec9e5/test/unit/persisters/sqlite.ts#L52-L123) but I can't figure out what the problem is.
- The remaining 12 failures are test for partial persists. I tried to implement partial changes without using ON CONFLICT (basically following the "good but tedious" option from [here](https://stackoverflow.com/a/4330694) but end up with a lot of tedious code and am not really sure about the value of this. Do you think it would be feasible to just don't write partial updates for this persister? From what I understand this would only mean rewriting some columns that are unchanged, or am I missing something?

2024-03-05 15:42 UTC, jamesgpearce commented
OK I'll take a look! I found some broken tests in the v( beta branch and this might be similar. Leave it with me.

2024-03-11 20:28 UTC, jamesgpearce commented
@bndkt please take a look at https://github.com/tinyplex/tinybase/pull/133/commits/51f1a2989e0dbafa87135cd40aec6f28566c44d4 - I simplified and isolated a simple (JSON-based) test that fails. The second write to the table (that has `"c1":2`) does not fire a change and so the test fails.

I read [here](https://docs.powersync.com/usage/installation/client-side-setup/instantiate-powersync-database) that there should not be more than one instance per database file. Maybe that's why you had the factory pattern, but it still doesn't seem to be a singleton. However, that didn't seem to fix it.

How well does this mock work do you think?

2024-03-22 14:37 UTC, jamesgpearce commented
@bndkt a gentle ping to see if you have any thoughts on this mock issue

2024-03-25 05:13 UTC, bndkt commented
@jamesgpearce Thanks for isolating this! I'm looking into it now, and see how to improve the mock in order to get the tests to pass.

2024-03-26 03:54 UTC, bndkt commented
@jamesgpearce in order to debug the mock function, I've temporarily enabled "on conflict" usage for the persister, so that it should behave exactly like the SQLite3 persister. I now get 2 failing tests. I've added comments to those and will tag you. They both seem to be timing-related, do you have any idea why the timing could be off here?

2024-03-26 03:56 UTC, bndkt commented on test/unit/persisters/persister-sqlite-tabular.test.ts
> +      // FAILS
@jamesgpearce 

when I duplicate all the `await pause(autoLoadPause);` calls in this test (to await the autoLoadPause two times), this test succeeds.

<img width="754" alt="Screenshot 2024-03-26 at 11 55 44 AM" src="https://github.com/tinyplex/tinybase/assets/91166910/2915fa2c-1a2e-4585-9756-e56ebb50e339">

2024-03-26 03:57 UTC, bndkt commented on test/unit/persisters/persisters.test.ts
> +  // FAILS
@jamesgpearce 
![Uploading Screenshot 2024-03-26 at 11.57.30 AM.png…]()

2024-03-28 18:22 UTC, jamesgpearce commented on test/unit/persisters/persister-sqlite-tabular.test.ts
> +      // FAILS
I can't repro success by adding in the second pause. It still doesn't work. No 'change' event seems to fire from the mock, so the autoloading doesn't know to pick up a change.

2024-04-02 05:47 UTC, bndkt commented
Oh wow, thanks for discovering this @jamesgpearce! I'll have a final look now and then set it to ready for review.

2024-04-02 11:24 UTC, bndkt commented
Good to go @jamesgpearce!

2024-04-04 15:55 UTC, merged

2024-04-04 15:56 UTC, jamesgpearce commented
Alright! Let's do any final polish in `main`.

2024-04-04 16:05 UTC, jamesgpearce commented
Thanks so much for your work on this!